services:
  Webgriffe\SyliusBackInStockNotificationPlugin\Command\AlertCommand:
    tags: ['console.command']
    arguments:
      - '@logger'
      - '@sylius.email_sender'
      - '@sylius.availability_checker'
      - '@sylius.repository.product_variant'
      - '@app.repository.back_in_stock_notification'
      - '@sylius.repository.channel'

  Webgriffe\SyliusBackInStockNotificationPlugin\Controller\SubscriptionController:
    tags: ['controller.service_arguments']
    arguments:
      - '@sylius.context.channel'
      - '@translator.data_collector'
      - '@debug.validator'
      - '@sylius.context.customer'
      - '@sylius.availability_checker.default'
      - '@sylius.repository.product_variant'
      - '@sylius.email_sender'
      - '@sylius.context.locale'
      - '@sylius.repository.customer'
      - '@app.repository.back_in_stock_notification'
      - '@app.factory.back_in_stock_notification'

  Webgriffe\SyliusBackInStockNotificationPlugin\Menu\BackInStockNotificationMenuItemAdder:
    tags:
      - { name: kernel.event_listener, event: sylius.menu.shop.account, method: addMenuItems }